version: '3'
services:
    web: 
        build: .
        ports:
            - "3000:3000"
        tty: true
        stdin_open: true
        volumes:
            - /app/node_modules
            - ./:/app