version: '3'
services: 
  mongo: 
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"

  redis: 
    image: 'redis:latest'
    restart: always
    ports: 
      - "6379:6379"

  aws_service:
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile
      context: ./aws_service
    volumes: 
      - /aws_app/node_modules
      - ./aws_service:/aws_app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=37017
      - MONGODB_USER=root
      - MONGODB_PASS=password123
    links:
      - mongo
      - redis
    ports:
      - "5000:5000"

  nginx: 
    depends_on:
      - aws_service
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx