apiVersion: apps/v1
kind: Deployment
metadata:
    name: aws-service-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: aws-service
    template:
        metadata:
            labels:
                component: aws-service 
        spec:
            containers:
                - name: aws-service
                  image: stephendrider/multi-server
                  ports:
                    - containerPort: 5000
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_PORT
                      value: 6379
                    - name: MONGO_USER
                      value: root
                    - name: MONGO_HOST
                      value: mongo-cluster-ip-service
                    - name: MONGO_PORT
                      value: 27017