apiVersion: v1
kind: Service
metadata:
    name: aws-service-cluster-ip-service
spec: 
    type: ClusterIP
    selector:
        component: aws-service
    ports:
        - port: 5000
          targetPort: 5000