apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-deployment
spec: 
    replicas: 1
    selector: 
        matchLabels:
            component: mongo
    template:
        metadata:
            labels:
                component: mongo
        spec:
            volumes:
                - name: mongodb-storage
                  persistentVolumeClaim:
                    claimName: mongodb-persistent-volume-claim
            containers:
                - name: mongo
                  image: mongo
                  ports:
                    - containerPort: 27017
                  volumeMounts:
                    - name: mongodb-storage
                      mountPath: /data/db
                      subPath: mongodb